# main menu
[[main]]
name = "Accueil"
url = "/"
weight = 1

[[main]]
name = "La Carte Collect'"
url = "carte-collect/"
weight = 3

[[main]]
name = "Contact"
url = "contact/"
weight = 4

# footer menu left
[[__thishides__footer_left]]
name = "About Us"
url = "#"

[[__thishides__footer_left]]
name = "Quick Start"
url = "#"

[[__thishides__footer_left]]
name = "Pricing"
url = "pricing/"


# footer menu middle
[[__thishides__footer_middle]]
name = "Pricing"
url = "pricing/"

[[__thishides__footer_middle]]
name = "Platform"
url = "#"

[[__thishides__footer_middle]]
name = "Features"
url = "#"

# footer menu right
[[__thishides__footer_right]]
name = "Privacy Policy"
url = "privacy-policy/"

[[__thishides__footer_right]]
name = "Terms & Conditions"
url = "terms-conditions/"

[[__thishides__footer_right]]
name = "FAQ"
url = "faq/"
